---
title: "Global rsofun run"
author: "Beni Stocker"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{map2tidy functionality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source_files <- list.files(here::here("R/"), "*.R$")  # locate all .R files
purrr::map(paste0(here::here("R/"), source_files), ~source(.)) 
```

## Specify settings

```{r}
settings <- list(
  model = "pmodel",
  year_start = 2018,  # xxx not yet handled
  year_end = 2018,  # xxx not yet handled
  lonmin = -180,  # xxx not yet handled
  lonmax = 180,  # xxx not yet handled
  latmin = -60,  # xxx not yet handled
  latmax = 85,  # xxx not yet handled
  source_climate = "watch-wfdei",
  dir_climate = "~/data/watch_wfdei",
  dir_climate_tidy = "~/data/watch_wfdei/tidy/",
  source_fapar = "modis",
  file_fapar = "~/data/MODIS-C006_MOD15A2_LAI_FPAR_zmaw/MODIS-C006_MOD15A2__LAI_FPAR__LPDAAC__GLOBAL_0.5degree__UHAM-ICDC__2000_2018__MON__fv0.02.nc",
  dir_fapar_tidy = "~/data/MODIS-C006_MOD15A2_LAI_FPAR_zmaw/tidy/",
  file_whc = "~/data/mct_data/cwdx80_forcing_halfdeg.nc",
  dir_whc_tidy = "~/data/mct_data/tidy/",
  file_landmask = "~/data/archive_legacy/landmasks/WFDEI-elevation.nc",
  dir_landmask_tidy = "~/data/archive_legacy/landmasks/WFDEI-elevation_tidy/",
  file_elv = "~/data/archive_legacy/landmasks/WFDEI-elevation.nc",
  dir_elv_tidy = "~/data/archive_legacy/landmasks/WFDEI-elevation_tidy/",
  overwrite = TRUE,
  spinupyears = 10,
  recycle = 1,
  dir_out = "xxx",
  dir_out_nc = "xxx",
  save_nc = list(
    gpp = "mon"
  ),
  nthreads = 1
)
```


## Specify model parameters

```{r}
par <- list(
  kphio              = 0.04998,    # setup ORG in Stocker et al. 2020 GMD
  kphio_par_a        = 0.0,        # set to zero to disable temperature-dependence of kphio
  kphio_par_b        = 1.0,
  soilm_thetastar    = 0.6 * 240,  # to recover old setup with soil moisture stress
  soilm_betao        = 0.0,
  beta_unitcostratio = 146.0,
  rd_to_vcmax        = 0.014,      # value from Atkin et al. 2015 for C3 herbaceous
  tau_acclim         = 30.0,
  kc_jmax            = 0.41
)
```

## Run the model

```{r}
out <- grsofun(
  par,
  settings
)
```

## Forcing data

### WATCH-WFDEI

Get data from all available files for each variable into a tidy format.
```{r}
df <- get_forcing(
  source_climate = "watch-wfdei",
  dir_climate = "~/data/watch_wfdei/",
  source_fapar = "modis",
  dir_fapar = "~/xxx"
)
```

This is only one year and only three variables: 1.7 GB. => Need to chunk all data first, then run rsofun by chunks.
```{r}
# in GB
object.size(df) * 1e-9
```

